# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-16 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读量')),
                ('like_num', models.IntegerField(default=0, verbose_name='喜欢量')),
                ('cove_img', models.ImageField(blank=True, null=True, upload_to='static/media/cover', verbose_name='封面图片')),
            ],
            options={
                'verbose_name': '文章列表',
                'verbose_name_plural': '文章列表',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('isNav', models.BooleanField(default=0, verbose_name='是否显示在导航栏')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='articletype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleType', verbose_name='分类'),
        ),
    ]
